### ISSUE TITLE
postcss-prefix-wrapper 对 font-family 处理有误

### ISSUE THREAD

**Issue by Cweili** [aliyun/alibabacloud-alfa#63]
配置：
```js
postcssPrefixWrapper({
  stackableRoot: '.A-B',
  repeat: 1,
  overrideIds: false,
}),
```

源码：
```css
.a {
  font-family: inherit;
}

.b {
  font-family: -apple-system;
}
```

编译后：
```css
.A-B .a {
  font-family: .ABinherit;
}

.A-B .b {
  font-family: .AB-apple-system;
}
```
